// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebVisualGame_MVC.Data;

namespace WebVisualGame_MVC.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190223153839_CreateTablesForGame")]
    partial class CreateTablesForGame
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebVisualGame_MVC.Data.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.Property<double>("Rating");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UrlIcon")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("WebVisualGame_MVC.Data.GameData.PointDialogue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Background_imageURL")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int?>("GameId");

                    b.Property<int>("StateNumber");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("PointDialogue");
                });

            modelBuilder.Entity("WebVisualGame_MVC.Data.GameData.Transition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GameId");

                    b.Property<int>("NextPoint");

                    b.Property<int>("NumberInList");

                    b.Property<int>("StartPoint");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Transition");
                });

            modelBuilder.Entity("WebVisualGame_MVC.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebVisualGame_MVC.Data.GameData.PointDialogue", b =>
                {
                    b.HasOne("WebVisualGame_MVC.Data.Game")
                        .WithMany("pointDialogues")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("WebVisualGame_MVC.Data.GameData.Transition", b =>
                {
                    b.HasOne("WebVisualGame_MVC.Data.Game")
                        .WithMany("transitions")
                        .HasForeignKey("GameId");
                });
#pragma warning restore 612, 618
        }
    }
}
